dashboards/urls.py
from django.urls import path
from dashboards.views import (AppealList
                              )

app_name = 'dashboards'

urlpatterns = [
    path('', AppealList.as_view(), name="dashboard"),

]

pages/urls.py
from django.urls import path
from pages.views import (
authentication_signin_basic,
authentication_signin_cover,
authentication_signup_basic,
authentication_signup_cover,
authentication_pass_reset_basic,
authentication_pass_reset_cover,
authentication_lockscreen_basic,
authentication_lockscreen_cover,
authentication_logout_basic,
authentication_logout_cover,
authentication_success_msg_basic,
authentication_success_msg_cover,
authentication_twostep_basic,
authentication_twostep_cover,
authentication_404_basic,
authentication_404_cover,
authentication_404_alt,
authentication_500,
authentication_pass_change_basic,
authentication_pass_change_cover,
authentication_offline,
pages_starter,
pages_maintenance,
pages_coming_soon,
)

app_name = "pages"

urlpatterns = [



    # Authentication
    path("authentication/signin-basic",view =authentication_signin_basic,name="authentication.signin_basic"),
    path("authentication/signin-cover",view =authentication_signin_cover,name="authentication.signin_cover"),
    path("authentication/signup-basic",view =authentication_signup_basic,name="authentication.signup_basic"),
    path("authentication/signup-cover",view =authentication_signup_cover,name="authentication.signup_cover"),
    path("authentication/password-reset-basic",view =authentication_pass_reset_basic,name="authentication.pass_reset_basic"),
    path("authentication/password-reset-cover",view =authentication_pass_reset_cover,name="authentication.pass_reset_cover"),
    path("authentication/lockscreen-basic",view =authentication_lockscreen_basic,name="authentication.lockscreen_basic"),
    path("authentication/lockscreen-cover",view =authentication_lockscreen_cover,name="authentication.lockscreen_cover"),
    path("authentication/logout-basic",view =authentication_logout_basic,name="authentication.logout_basic"),
    path("authentication/logout-cover",view =authentication_logout_cover,name="authentication.logout_cover"),
    path("authentication/success-msg-basic",view =authentication_success_msg_basic,name="authentication.success_msg_basic"),
    path("authentication/success-msg-cover",view =authentication_success_msg_cover,name="authentication.success_msg_cover"),
    path("authentication/two-step-authentication-basic",view =authentication_twostep_basic,name="authentication.twostep_basic"),
    path("authentication/two-step-authentication-cover",view =authentication_twostep_cover,name="authentication.twostep_cover"),
    path("authentication/404-basic",view =authentication_404_basic,name="authentication.404_basic"),
    path("authentication/404-cover",view =authentication_404_cover,name="authentication.404_cover"),
    path("authentication/404-alt",view =authentication_404_alt,name="authentication.404_alt"),
    path("authentication/500",view =authentication_500,name="authentication.500"),
    path("authentication/pass-change-basic",view =authentication_pass_change_basic,name="authentication.pass_change_basic"),
    path("authentication/pass-change-cover",view =authentication_pass_change_cover,name="authentication.pass_change_cover"),
    path("authentication/offline",view =authentication_offline,name="authentication.offline"),
    
    # Pages              
    path("pages/starter-page",view =pages_starter,name="pages.starter"),
    
    path("pages/maintenance",view =pages_maintenance,name="pages.maintenance"),
    path("pages/coming-soon",view =pages_coming_soon,name="pages.coming_soon"),
   
] 

velzon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import MyPasswordChangeView, MyPasswordSetView

urlpatterns = [
    path('admin/', admin.site.urls),
    # Dashboard
    path('', include('dashboards.urls')),

    # Layouts
    path('layouts/', include('layouts.urls')),

    # Pages
    path('pages/', include('pages.urls')),
    path(
        "account/password/change/",
        login_required(MyPasswordChangeView.as_view()),
        name="account_change_password",
    ),
    path(
        "account/password/set/",
        login_required(MyPasswordSetView.as_view()),
        name="account_set_password",
    ),
    # All Auth 
    path('account/', include('allauth.urls')),
]

templates/pages/authentication/auth-404-alt.html
{% load static %}
<!DOCTYPE html>
<html lang="en" {% block html %}data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg"{% endblock html %}>
    <head>
        <meta charset="utf-8" />
        <title>404 Error alt | Velzon - Admin & Dashboard Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="Themesbrand" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">

        <!-- Layout config Js -->
        <script src="{% static 'js/layout.js'%}"></script>
        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
        <!-- custom Css-->
        <link href="{% static 'css/custom.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <!-- auth-page wrapper -->
        <div class="auth-page-wrapper auth-bg-cover py-5 d-flex justify-content-center align-items-center min-vh-100">
            <div class="bg-overlay"></div>
            <!-- auth-page content -->
            <div class="auth-page-content overflow-hidden pt-lg-5">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-xl-5">
                            <div class="card overflow-hidden">
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <lord-icon class="avatar-xl"
                                        src="https://cdn.lordicon.com/spxnqpau.json"
                                        trigger="loop"
                                        colors="primary:#405189,secondary:#0ab39c">
                                        </lord-icon>
                                        <h1 class="text-primary mb-4">Oops !</h1>
                                        <h4 class="text-uppercase">Sorry, Page not Found 😭</h4>
                                        <p class="text-muted mb-4">The page you are looking for not available!</p>
                                        <a href="{% url 'dashboards:dashboard'%}" class="btn btn-success"><i class="mdi mdi-home me-1"></i>Back to home</a>
                                    </div>
                                </div>
                            </div>
                            <!-- end card -->
                        </div>
                        <!-- end col -->
    
                    </div>
                    <!-- end row -->
                </div>
                <!-- end container -->
            </div>
            <!-- end auth page content -->
        </div>
        <!-- end auth-page-wrapper -->

        <!-- JAVASCRIPT -->
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
        <script src="{% static 'libs/simplebar/dist/simplebar.min.js'%}"></script>
        <script src="{% static 'libs/node-waves/dist/waves.min.js'%}"></script>
        <script src="{% static 'libs/feather-icons/dist/feather.min.js'%}"></script>
        <script src="{% static 'js/pages/plugins/lord-icon-2.1.0.js'%}"></script>
        <script src="{% static 'js/plugins.js'%}"></script>
    </body>
</html>

templates/pages/authentication/auth-404-basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg">
    <head>
        <meta charset="utf-8" />
        <title>404 Error Basic | Velzon - Admin & Dashboard Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="Themesbrand" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">

        <!-- Layout config Js -->
        <script src="{% static 'js/layout.js'%}"></script>
        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
        <!-- custom Css-->
        <link href="{% static 'css/custom.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div class="auth-page-wrapper pt-5">
            <!-- auth page bg -->
            <div class="auth-one-bg-position auth-one-bg"  id="auth-particles">
                <div class="bg-overlay"></div>
                
                <div class="shape">
                    <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1440 120">
                        <path d="M 0,36 C 144,53.6 432,123.2 720,124 C 1008,124.8 1296,56.8 1440,40L1440 140L0 140z"></path>
                    </svg>
                </div>
            </div>

            <!-- auth page content -->
            <div class="auth-page-content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="text-center pt-4">
                                <div class="">
                                    <img src="{% static 'images/error.svg'%}" alt="" class="error-basic-img move-animation">
                                </div>
                                <div class="mt-n4">
                                    <h1 class="display-1 fw-medium">404</h1>
                                    <h3 class="text-uppercase">Sorry, Page not Found 😭</h3>
                                    <p class="text-muted mb-4">The page you are looking for not available!</p>
                                    <a href="{% url 'dashboards:dashboard'%}" class="btn btn-success"><i class="mdi mdi-home me-1"></i>Back to home</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- end row -->

                </div>
                <!-- end container -->
            </div>
            <!-- end auth page content -->

            <!-- footer -->
            <footer class="footer">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="text-center">
                                <p class="mb-0 text-muted">&copy; <script>document.write(new Date().getFullYear())</script> Velzon. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand</p>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <!-- end Footer -->

        </div>
        <!-- end auth-page-wrapper -->

        <!-- JAVASCRIPT -->
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
        <script src="{% static 'libs/simplebar/dist/simplebar.min.js'%}"></script>
        <script src="{% static 'libs/node-waves/dist/waves.min.js'%}"></script>
        <script src="{% static 'libs/feather-icons/dist/feather.min.js'%}"></script>
        <script src="{% static 'js/pages/plugins/lord-icon-2.1.0.js'%}"></script>
        <script src="{% static 'js/plugins.js'%}"></script>
        <!-- particles js -->
        <script src="{% static 'libs/particles.js/particles.js'%}"></script>
        <!-- particles app js -->
        <script src="{% static 'js/pages/particles.app.js'%}"></script>
    </body>
</html>

templates/pages/authentication/auth-500.html
{% load static %}
<!DOCTYPE html>
<html lang="en" {% block html %}data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg"{% endblock html %}>
    <head>
        <meta charset="utf-8" />
        <title>500 Error | Velzon - Admin & Dashboard Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="Themesbrand" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">

        <!-- Layout config Js -->
        <script src="{% static 'js/layout.js'%}"></script>
        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
        <!-- custom Css-->
        <link href="{% static 'css/custom.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <!-- auth-page wrapper -->
        <div class="auth-page-wrapper py-5 d-flex justify-content-center align-items-center min-vh-100">

            <!-- auth-page content -->
            <div class="auth-page-content overflow-hidden p-0">
                <div class="container-fluid">
                    <div class="row justify-content-center">
                        <div class="col-xl-4 text-center">
                            <div class="error-500 position-relative">
                                <img src="{% static 'images/error500.png'%}" alt="" class="img-fluid error-500-img error-img" />
                                <h1 class="title text-muted">500</h1>
                            </div>
                            <div>
                                <h4>Internal Server Error!</h4>
                                <p class="text-muted w-75 mx-auto">Server Error 500. We're not exactly sure what happened, but our servers say something is wrong.</p>
                                <a href="{% url 'dashboards:dashboard'%}" class="btn btn-success"><i class="mdi mdi-home me-1"></i>Back to home</a>
                            </div>
                        </div><!-- end col-->
                    </div>
                    <!-- end row -->
                </div>
                <!-- end container -->
            </div>
            <!-- end auth-page content -->
        </div>
        <!-- end auth-page-wrapper -->
    </body>
</html>

templates/pages/authentication/auth-lockscreen-basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en" {% block html %}data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg"{% endblock html %}>
    <head>
        <meta charset="utf-8" />
        <title>Lock Screen | Velzon - Admin & Dashboard Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="Themesbrand" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">

        <!-- Layout config Js -->
        <script src="{% static 'js/layout.js'%}"></script>
        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
        <!-- custom Css-->
        <link href="{% static 'css/custom.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div class="auth-page-wrapper pt-5">
            <!-- auth page bg -->
            <div class="auth-one-bg-position auth-one-bg"  id="auth-particles">
                <div class="bg-overlay"></div>
                
                <div class="shape">
                    <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1440 120">
                        <path d="M 0,36 C 144,53.6 432,123.2 720,124 C 1008,124.8 1296,56.8 1440,40L1440 140L0 140z"></path>
                    </svg>
                </div>
            </div>

            <!-- auth page content -->
            <div class="auth-page-content">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="text-center mt-sm-5 mb-4 text-white-50">
                                <div>
                                    <a href="{% url 'dashboards:dashboard'%}" class="d-inline-block auth-logo">
                                        <img src="{% static 'images/logo-light.png'%}" alt="" height="20">
                                    </a>
                                </div>
                                <p class="mt-3 fs-15 fw-medium">Premium Admin & Dashboard Template</p>
                            </div>
                        </div>
                    </div>
                    <!-- end row -->

                    <div class="row justify-content-center">
                        <div class="col-md-8 col-lg-6 col-xl-5">
                            <div class="card mt-4">
                            
                                <div class="card-body p-4"> 
                                    <div class="text-center mt-2">
                                        <h5 class="text-primary">Lock Screen</h5>
                                        <p class="text-muted">Enter your password to unlock the screen!</p>
                                    </div>
                                    <div class="user-thumb text-center">
                                        <img src="{% static 'images/users/avatar-1.jpg'%}" class="rounded-circle img-thumbnail avatar-lg" alt="thumbnail">
                                        <h5 class="font-size-15 mt-3">Anna Adame</h5>
                                    </div>
                                    <div class="p-2 mt-4">
                                        <form>
                                            <div class="mb-3">
                                                <label class="form-label" for="userpassword">Password</label>
                                                <input type="password" class="form-control" id="userpassword" placeholder="Enter password" required>
                                            </div>
                                            <div class="mb-2 mt-4">
                                                <button class="btn btn-success w-100" type="submit">Unlock</button>
                                            </div>
                                        </form><!-- end form -->

                                    </div>
                                </div>
                                <!-- end card body -->
                            </div>
                            <!-- end card -->

                            <div class="mt-4 text-center">
                                <p class="mb-0">Not you ? return <a href="{% url 'pages:authentication.signin_basic' %}" class="fw-semibold text-primary text-decoration-underline"> Signin </a> </p>
                            </div>

                        </div>
                    </div>
                    <!-- end row -->
                </div>
                <!-- end container -->
            </div>
            <!-- end auth page content -->

            <!-- footer -->
            <footer class="footer">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="text-center">
                                <p class="mb-0 text-muted">&copy; <script>document.write(new Date().getFullYear())</script> Velzon. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand</p>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <!-- end Footer -->
        </div>
        <!-- end auth-page-wrapper -->

        <!-- JAVASCRIPT -->
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
        <script src="{% static 'libs/simplebar/dist/simplebar.min.js'%}"></script>
        <script src="{% static 'libs/node-waves/dist/waves.min.js'%}"></script>
        <script src="{% static 'libs/feather-icons/dist/feather.min.js'%}"></script>
        <script src="{% static 'js/pages/plugins/lord-icon-2.1.0.js'%}"></script>
        <script src="{% static 'js/plugins.js'%}"></script>
        <!-- particles js -->
        <script src="{% static 'libs/particles.js/particles.js'%}"></script>
        <!-- particles app js -->
        <script src="{% static 'js/pages/particles.app.js'%}"></script>
    </body>
</html>

templates/pages/authentication/auth-lockscreen-cover.html
{% load static %}
<!DOCTYPE html>
<html lang="en" {% block html %}data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg"{% endblock html %}>
    <head>
        <meta charset="utf-8" />
        <title>Lock Screen | Velzon - Admin & Dashboard Template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
        <meta content="Themesbrand" name="author" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">


        <!-- Layout config Js -->
        <script src="{% static 'js/layout.js'%}"></script>
        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
        <!-- custom Css-->
        <link href="{% static 'css/custom.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    </head>

    <body>

        <!-- auth-page wrapper -->
        <div class="auth-page-wrapper auth-bg-cover py-5 d-flex justify-content-center align-items-center min-vh-100">
        <div class="bg-overlay"></div>
        <!-- auth-page content -->
        <div class="auth-page-content overflow-hidden pt-lg-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card overflow-hidden">
                            <div class="row justify-content-center g-0">
                                <div class="col-lg-6">
                                    <div class="p-lg-5 p-4 auth-one-bg h-100">
                                        <div class="bg-overlay"></div>
                                        <div class="position-relative h-100 d-flex flex-column">
                                            <div class="mb-4">
                                                <a href="{% url 'dashboards:dashboard'%}" class="d-block">
                                                    <img src="{% static 'images/logo-light.png'%}" alt="" height="18">
                                                </a>
                                            </div>
                                            <div class="mt-auto">
                                                <div class="mb-3">
                                                    <i class="ri-double-quotes-l display-4 text-success"></i>
                                                </div>

                                                <div id="qoutescarouselIndicators" class="carousel slide" data-bs-ride="carousel">
                                                    <div class="carousel-indicators">
                                                        <button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="0" class="active"
                                                            aria-current="true" aria-label="Slide 1"></button>
                                                        <button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="1"
                                                            aria-label="Slide 2"></button>
                                                        <button type="button" data-bs-target="#qoutescarouselIndicators" data-bs-slide-to="2"
                                                            aria-label="Slide 3"></button>
                                                    </div>
                                                    <div class="carousel-inner text-center text-white-50 pb-5">
                                                        <div class="carousel-item active">
                                                            <p class="fs-15 fst-italic">" Great! Clean code, clean design, easy for customization. Thanks very much! "</p>
                                                        </div>
                                                        <div class="carousel-item">
                                                            <p class="fs-15 fst-italic">" The theme is really great with an amazing customer support."</p>
                                                        </div>
                                                        <div class="carousel-item">
                                                            <p class="fs-15 fst-italic">" Great! Clean code, clean design, easy for customization. Thanks very much! "</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- end carousel -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end col -->

                                <div class="col-lg-6">
                                    <div class="p-lg-5 p-4">
                                        <div>
                                            <h5 class="text-primary">Lock Screen</h5>
                                            <p class="text-muted">Enter your password to unlock the screen!</p>
                                        </div>
                                        <div class="user-thumb text-center">
                                            <img src="{% static 'images/users/avatar-1.jpg'%}" class="rounded-circle img-thumbnail avatar-lg" alt="thumbnail">
                                            <h5 class="font-size-15 mt-3">Anna Adame</h5>
                                        </div>
        
                                        <div class="mt-4">
                                            <form>
                                                <div class="mb-3">
                                                    <label class="form-label" for="userpassword">Password</label>
                                                    <input type="password" class="form-control" id="userpassword" placeholder="Enter password" required>
                                                </div>
                                                <div class="mb-2 mt-4">
                                                    <button class="btn btn-success w-100" type="submit">Unlock</button>
                                                </div>
                                            </form><!-- end form -->
                                        </div>

                                        <div class="mt-5 text-center">
                                            <p class="mb-0">Not you ? return <a href="{% url 'pages:authentication.signin_cover' %}" class="fw-semibold text-primary text-decoration-underline"> Signin</a></p>
                                        </div>
                                    </div>
                                </div>
                                <!-- end col -->
                            </div>
                            <!-- end row -->
                        </div>
                        <!-- end card -->
                    </div>
                    <!-- end col -->

                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end auth page content -->

        <!-- footer -->
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center">
                            <p class="mb-0">&copy; <script>document.write(new Date().getFullYear())</script> Velzon. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand</p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end Footer -->
        </div>
        <!-- end auth-page-wrapper -->

        <!-- JAVASCRIPT -->
        <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
        <script src="{% static 'libs/simplebar/dist/simplebar.min.js'%}"></script>
        <script src="{% static 'libs/node-waves/dist/waves.min.js'%}"></script>
        <script src="{% static 'libs/feather-icons/dist/feather.min.js'%}"></script>
        <script src="{% static 'js/pages/plugins/lord-icon-2.1.0.js'%}"></script>
        <script src="{% static 'js/plugins.js'%}"></script>
    </body>

</html>